//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploEntity.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_Setores
    {
        public Cad_Setores()
        {
            this.Cad_Profissoes = new HashSet<Cad_Profissoes>();
        }
    
        public int Set_ID { get; set; }
        public string Set_Nome { get; set; }
        public string Set_Descricao { get; set; }
        public Nullable<System.DateTime> Set_DtInc { get; set; }
        public Nullable<System.DateTime> Set_DtAlt { get; set; }
        public Nullable<System.DateTime> Set_DtExc { get; set; }
    
        public virtual ICollection<Cad_Profissoes> Cad_Profissoes { get; set; }
    }
}
