USE [master]
GO

/****** Object:  Database [CursoProgramacao]    Script Date: 02/04/2015 12:04:07 ******/
CREATE DATABASE [CursoProgramacao] ON  PRIMARY 
( NAME = N'CursoProgramacao', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.ECSQLEXPRESS\MSSQL\DATA\CursoProgramacao.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CursoProgramacao_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.ECSQLEXPRESS\MSSQL\DATA\CursoProgramacao_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CursoProgramacao] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CursoProgramacao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CursoProgramacao] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CursoProgramacao] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CursoProgramacao] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CursoProgramacao] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CursoProgramacao] SET ARITHABORT OFF 
GO

ALTER DATABASE [CursoProgramacao] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CursoProgramacao] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CursoProgramacao] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CursoProgramacao] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CursoProgramacao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CursoProgramacao] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CursoProgramacao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CursoProgramacao] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CursoProgramacao] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CursoProgramacao] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CursoProgramacao] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CursoProgramacao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CursoProgramacao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CursoProgramacao] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CursoProgramacao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CursoProgramacao] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CursoProgramacao] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CursoProgramacao] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CursoProgramacao] SET  READ_WRITE 
GO

ALTER DATABASE [CursoProgramacao] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CursoProgramacao] SET  MULTI_USER 
GO

ALTER DATABASE [CursoProgramacao] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CursoProgramacao] SET DB_CHAINING OFF 
GO





USE [CursoProgramacao]
GO

/****** Object:  Table [dbo].[Cad_Setores]    Script Date: 02/04/2015 12:04:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Cad_Setores](
	[Set_ID] [int] IDENTITY(1,1) NOT NULL,
	[Set_Nome] [varchar](50) NULL,
	[Set_Descricao] [varchar](300) NULL,
	[Set_DtInc] [datetime] NULL,
	[Set_DtAlt] [datetime] NULL,
	[Set_DtExc] [datetime] NULL,
 CONSTRAINT [PK_Cad_Setores] PRIMARY KEY CLUSTERED 
(
	[Set_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Cad_Profissoes](
	[Pro_ID] [int] IDENTITY(1,1) NOT NULL,
	[Pro_Nome] [varchar](50) NULL,
	[Pro_Descricao] [varchar](300) NULL,
	[Pro_DtInc] [datetime] NULL,
	[Pro_DtAlt] [datetime] NULL,
	[Pro_DtExc] [datetime] NULL,
 CONSTRAINT [PK_Cad_Profissoes] PRIMARY KEY CLUSTERED 
(
	[Pro_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[Cad_ProfSetAtuacao]    Script Date: 02/04/2015 12:05:38 ******/
CREATE TABLE [dbo].[Cad_ProfSetAtuacao](
	[SetA_ProID] [int] NOT NULL,
	[SetA_SetID] [int] NOT NULL,
 CONSTRAINT [PK_Cad_ProfSetAtuacao] PRIMARY KEY CLUSTERED 
(
	[SetA_ProID] ASC,
	[SetA_SetID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Cad_ProfSetAtuacao]  WITH CHECK ADD  CONSTRAINT [Cad_Profissoes_Cad_ProfSetAtuacao_FK] FOREIGN KEY([SetA_ProID])
REFERENCES [dbo].[Cad_Profissoes] ([Pro_ID])
GO

ALTER TABLE [dbo].[Cad_ProfSetAtuacao] CHECK CONSTRAINT [Cad_Profissoes_Cad_ProfSetAtuacao_FK]
GO

ALTER TABLE [dbo].[Cad_ProfSetAtuacao]  WITH CHECK ADD  CONSTRAINT [Cad_Setores_Cad_ProfSetAtuacao_FK] FOREIGN KEY([SetA_SetID])
REFERENCES [dbo].[Cad_Setores] ([Set_ID])
GO

ALTER TABLE [dbo].[Cad_ProfSetAtuacao] CHECK CONSTRAINT [Cad_Setores_Cad_ProfSetAtuacao_FK]
GO

SET ANSI_PADDING OFF
GO