//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profissao
    {
        public Profissao()
        {
            this.Cad_Setores = new HashSet<Setor>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DtInclusao { get; set; }
        public Nullable<System.DateTime> DtAlteracao { get; set; }
        public Nullable<System.DateTime> DtExclusao { get; set; }
    
        public virtual ICollection<Setor> Cad_Setores { get; set; }
    }
}
